---
branches:
  - main
projects:
  BetterMultiWorld:
    path: ''
    icon: icon.png
    libs:
      Commando:
        src: CortexPE/Commando/Commando
        version: ^3.3.0
      libpmform:
        src: CzechPMDevs/libpmform/libpmform
        version: ^1.1.0
      VanillaGenerator:
        src: CzechPMDevs/VanillaGenerator/VanillaGenerator
        version: ^0.0.6
    lint:
      phpstan: true
...
